### ISSUE TITLE
[Bug]: Chat input panel overlaps content for small width

### ISSUE THREAD

**Issue by felixblaschke** [pnd280/complexity#11]
### Version

0.0.1.7

### Describe the bug

I used it in a sidebar kind of manner with a small width window. The chat input panel overlaps with the content (related prompts)

### Steps to reproduce

- Reduce window size to small
- Enter prompt
- Observe related prompts is covered by chat input panel

### Bug confirmation

- [X] I am not able to reproduce the issue with the extension disabled
- [X] I have re-installed the extension and the issue persists

### Expected behavior

Additional whitespace at the bottom (like it's behaving without extension)

### Screenshots

<img width="613" alt="Screenshot 2024-09-12 at 10 18 56" src="https://github.com/user-attachments/assets/ea4e8955-2ac8-45b2-80ed-71076c59c7ed">

### Browser

Chrome 128

**Comment by pnd280** [comment]
the update is pending review, in case you don't want to wait: https://github.com/pnd280/complexity/releases/tag/v0.0.1.8-alpha (signed by the store)
