### ISSUE TITLE
[Bug]: Unable to switch languages

### ISSUE THREAD

**Issue by shiquda** [pnd280/complexity#16]
### Version

0.0.3.9

### Describe the bug

When I switch the language from English to Chinese with the extention enabled, it just recover to English if I refresh the page. However it won't recover to English if I turn off the extension.
![PixPin_2024-10-05_19-38-04](https://github.com/user-attachments/assets/34a469d2-8aaa-4046-96e2-2ca78fa0df9d)

### Steps to reproduce

1. Enable the extension
2. Set language to Chinese
3. Refresh

### Bug confirmation

- [X] I am not able to reproduce the issue with the extension disabled
- [X] I have re-installed the extension and the issue persists

### Expected behavior

The language should be Chinese.

### Browser

Microsoft Edge 129.0.2792.79

### Additional context

The extension was installed from chrome web extension store.

**Comment by shiquda** [comment]
Sorry for not viewing the information from the [offitial site](https://cplx.vercel.app/). 
> As of now, in order for the extension to work properly, your Perplexity.ai user interface launguage must be set to English (en-US). Any translations settings/extensions/plugins are also not supported, please turn them off.

May you consider add support for other languages?

**Comment by DentistCode** [comment]
maybe u can add a pr called feature request

**Comment by DentistCode** [comment]
btw 

it's seem that the option doesnt effect the result

if u ask with chinese, the answer would come with chinese 

![Snipaste_2024-10-05_20-35-05](https://github.com/user-attachments/assets/9344bb31-4dd8-4684-baf5-6710d1e48860)

**Comment by pnd280** [comment]
Hi, @shiquda, as @DentistCode said, it only affects the user interface; your answers will still comply with your query/AI profile.

> May you consider adding support for other languages?

Yes, this is one of the top-prioritized enhancements.
