### ISSUE TITLE
[Feature Request]: File creation on long text paste button

### ISSUE THREAD

**Issue by Classic298** [pnd280/complexity#17]
### Feature Description

Move "No file creation on long text paste" from the settings to the main menu.

### Use Case

Sometimes, text pastes are too long to be able to even send the question to the AI. In those cases, it is necessary to upload it as file/have it be created as a file. But in other cases I want it to be pasted as a text and not as a file.

Move the setting from the complexity settings into the main menu so I can toggle with a single click whether file creation on long text pastes is turned on or off.

Consider using a tooltip (when doing a mouseover) that says "File creation on long text paste".

Alternatively there can be a dropdown menu with the two options (on and off) for more clarity.

The use case is so that you don't always have to go to the settings and change it back and forth everytime, instead you can do it right on the main menu.

**Comment by pnd280** [comment]
https://github.com/pnd280/complexity/commit/dcf9b3d6e90ad8ba841a2e7a4d409b93c017f447 Hold shift to bypass file creation. Normal paste will still create a file.

**Comment by Classic298** [comment]
nice thanks
