### ISSUE TITLE
[Bug]: Releases "spaces" section, AI prompt textInput box is limited

### ISSUE THREAD

**Issue by yyyyyyounger** [pnd280/complexity#22]
### Version

0.0.3.15

### Describe the bug

Thanks for the contribution to the perplexity.ai experience! ❤️
Perplexity just releases "spaces" section, AI prompt textinput box is limited. 
Cannot scroll down, hidden some input text.

### Steps to reproduce

1. Go to `https://www.perplexity.ai/spaces`
2. Create a space, edit some ai prompt
3. Refresh, Edit again the space AI prompt

### Bug confirmation

- [X] I am not able to reproduce the issue with the extension disabled
- [X] I have re-installed the extension and the issue persists

### Expected behavior

The size of the AI prompt input box should be larger or allow scrolling

### Screenshots

<img width="585" alt="image" src="https://github.com/user-attachments/assets/08b8df8b-fdd6-4039-a8ed-5f75ab754cb0">
⬆️ Disable Extension

<img width="592" alt="image" src="https://github.com/user-attachments/assets/f7d71fbf-7782-4f31-bf26-95e008e32423">
⬆️ Enable Extension(Cannot scroll)

### Browser

Google Chrome 130.0.6723.59

**Comment by joostshao** [comment]
welcome to pplx space!
