### ISSUE TITLE
[Bug]: Cromite compatibility

### ISSUE THREAD

**Issue by CrazyAce25** [pnd280/complexity#25]
### Version

v0.0.4.5

### Describe the bug

Your extention does not function within Cromite.  Its likely something that Cromite (https://github.com/uazo/cromite) changes but I have no idea what it is.  I was hoping if it was something simple like a permission or flag that could be altered as most other extensions I have used with Cromite function without an issuie.  

### Steps to reproduce

Install Cromite, load extension.

### Bug confirmation

- [X] I am not able to reproduce the issue with the extension disabled
- [X] I have re-installed the extension and the issue persists

### Expected behavior

Load up extension and have it function.

### Browser

Version 130.0.6723.59 (Official Build) (64-bit)

### Additional context

The extension does nothing other than load up peprlexity.ai in stock form and function.

**Comment by pnd280** [comment]
I unable to reproduce the issue, here are things you can try:
- Try the extension in a new profile to make sure there's no conflicts
- Provide logs in the browser's console and in the extension's page.

![image](https://github.com/user-attachments/assets/37dc9621-d78b-457f-afcc-fd620f10c5d8)
![image](https://github.com/user-attachments/assets/b67e73e4-4771-4391-bf30-ef0050b4e113)

**Comment by CrazyAce25** [comment]
![image](https://github.com/user-attachments/assets/cfe36d8b-744d-4902-a7a5-a0b170962e1f)
![image](https://github.com/user-attachments/assets/a2932c67-6dd1-45fc-bc8a-6839a1119da2)
![image](https://github.com/user-attachments/assets/583aa729-9475-4fb4-a7ba-2ee9c223a97e)
New profile didnt change the situation.

**Comment by pnd280** [comment]
@CrazyAce25 the extension works as expected, what went wrong here?

**Comment by CrazyAce25** [comment]
> @CrazyAce25 the extension works as expected, what went wrong here?
![image](https://github.com/user-attachments/assets/0b85a95d-4c45-4fb2-92c3-e7a4d8f80d6a)
Could be I just dont know how to use the extension then.  Where are the optoins presented here?  
"Language Model
Switch Language Models quickly, including within threads. Options include legacy models: GPT-4 Turbo, Mistral Large, and Gemini Pro 1.0."   I figured there would be an option in the UI to selected the language model?

**Comment by pnd280** [comment]
@CrazyAce25 
To be able to use Space, you need to be logged in. The same goes for model selectors, you need to be logged in and subscribed to Perplexity Pro

**Comment by CrazyAce25** [comment]
Makes a ton more sense now.  Thank you.
