### ISSUE TITLE
[Bug]: System prompt disappears when starting a new thread in a space.

### ISSUE THREAD

**Issue by manwith33** [pnd280/complexity#29]
### Version

0.5.2

### Describe the bug

When I start a new thread in a space and ask Sonnett 3.5 to quote me the system prompt, it gives me the generic Perplexity Prompt without the custom Spaces prompt. If I disable Complexity and repeat this process, the Spaces system Prompt works. I'm pretty sure what's happening is new spaces threads aren't actually spaces threads, at least when complexity is running. Even though they were started in the spaces area they are not assigned spaces threads. 

### Steps to reproduce

On the main web site, I click Spaces on the left. Then I click the space I want to use. then I type in "Hello please before we begin quote me the system prompt" with Sonnet 3.5 set as default.

### Bug confirmation

- [X] I am not able to reproduce the issue with the extension disabled
- [X] I have re-installed the extension and the issue persists

### Expected behavior

Starting a new thread in the spaces screen would create a thread with the spaces system prompt. 

### Browser

chrome 130

**Comment by pnd280** [comment]
where do you start a new Space thread? from homepage via Complexity's Space selector or directly on the Space's page (`/collections/*`)?

**Comment by manwith33** [comment]
From the spaces page, the way you'd do it if Complexity were not installed:


<img width="716" alt="Capture" src="https://github.com/user-attachments/assets/0a486f3e-f12e-4606-a853-a8feb40e9bba">

**Comment by pnd280** [comment]
I mean where did the issue happen when the extension is enabled? On the Space's space or on the homepage via Complexity's Space selector? or both?

**Comment by manwith33** [comment]
It fails on the space's page. It works fine on the homepage with Complexity Space selector enabled.

**Comment by pnd280** [comment]
That's kinda weird because I'm expecting the opposite, the selector on the homepage is running into issues after latest update from Perplexity 🤔 I'll update as soon as I find anything. For now can you please **disable** the "Space & Focus selector" feature and let me know whether it fixes the issue?
![image](https://github.com/user-attachments/assets/1220f446-da34-453b-ab51-85987da25de3)

**Comment by manwith33** [comment]
I just tried it again and both the homescreen and the spaces screen were working properly.  I then tried disabling space and focus in settings and it made the spaces screen not work. 

One behavior I'm seeing a lot is the part where it tells you if the thread is part of the space is wrong, in this case it said +space like it's not in a space but it was, and hitting refresh revealed that it was in a space, I'm talking about that thing at the top:
<img width="394" alt="Capture" src="https://github.com/user-attachments/assets/ad52786c-70a5-4890-a1f3-15ba290ce532">

Other times it said the space name at the top instead of +space but it wasn't in that space, and hitting refresh revealed that.

**Comment by pnd280** [comment]
@manwith33 thank you for the confirmation, will look into it

**Comment by pnd280** [comment]
The latest update (version 0.0.5.6) should address all the issues mentioned in this thread, except for one:

> One behavior I'm seeing a lot is the part where it tells you if the thread is part of the space is wrong, in this case it said +space like it's not in a space but it was, and hitting refresh revealed that it was in a space

Unfortunately, this particular issue is not resolvable. Let me know if any other issues persist.
