### ISSUE TITLE
[Bug]: Clicking on complexity Icon doesn't open Perplexity website

### ISSUE THREAD

**Issue by shemul** [pnd280/complexity#36]
### Version

v0.0.5.8

### Describe the bug

Previously, clicking the completixity icon would open the perplexity site, but it's not working since yesterday.

### Steps to reproduce

Click on the Compleixty Icon on the chrome menu
it was supposed to open the perplexity website

### Bug confirmation

- [X] I am not able to reproduce the issue with the extension disabled
- [X] I have re-installed the extension and the issue persists

### Expected behavior

Open the perlplexity website

### Browser

Chrome 130.0.6723.117

**Comment by pnd280** [comment]
this is a deployment issue where I wrongly uploaded the firefox zip to the chrome web store 😅 fixed in the latest version 0.0.5.9 (available now on the store)
