### ISSUE TITLE
[Bug]: Completion is stuck on "Researching"

### ISSUE THREAD

**Issue by michalkkkd** [pnd280/complexity#37]
### Version

 0.0.5.9

### Describe the bug

As in title, every dozen prompts, once becomes completely stuck on 'Researching'. For every prompt, I refresh Perplexity and start on home page.

### Steps to reproduce

1. Enter prompt
2. Press submit
3. Becomes stuck on 'Researching'

### Bug confirmation

- [X] I am not able to reproduce the issue with the extension disabled
- [X] I have re-installed the extension and the issue persists

### Expected behavior

Not stuck on researching.

### Browser

Version 130.0.6723.117 (Official Build) (64-bit)

**Comment by pnd280** [comment]
I can't seem to reproduce this behavior, if it happens again, could you please share a screenshot + browser console logs?

**Comment by michalkkkd** [comment]
Sure, screenshot is possible, console logs are usually empty (I know, cause i have them open in general when using Perplexity)

**Comment by michalkkkd** [comment]
@pnd280 This is how it looks like. It happens on prompts regardless of their content. It gets stuck, and doesn't recover at all (waited 3-4 minutes).
![image](https://github.com/user-attachments/assets/a0a6b75e-8199-403c-851d-5e59bcb69c44)

**Comment by pnd280** [comment]
@michalkkkd where did you initialize this thread? on perplexity's or by search params `https://www.perplexity.ai/?q=something`?

**Comment by michalkkkd** [comment]
@pnd280 I only initiate threads using button in top left corner. Also always new threads. I dont usually do followups.

**Comment by chen1551317706** [comment]
me too

**Comment by pnd280** [comment]
please reopen this thread if the issue still persists in v1.x
