### ISSUE TITLE
[Bug]: remove Opus, openai OA1 and google Gemini 1.5 Pro

### ISSUE THREAD

**Issue by Fadyio** [pnd280/complexity#38]
### Version

v0.0.5.7

### Describe the bug

perplexity removed all these models 

### Steps to reproduce

Non

### Bug confirmation

- [X] I am not able to reproduce the issue with the extension disabled
- [X] I have re-installed the extension and the issue persists

### Expected behavior

Chrome

### Browser

Chrome

**Comment by michalkkkd** [comment]
@Fadyio How can i find information about model removals from perplexity? Whats the source? Of course Opus was on Reddit, but I didn't read anything about Gemini.

**Comment by para-droid-ai** [comment]
Great question the rest of the CPLX team would get great use out of as well. Their changes are usually random and erratic.

**Comment by pnd280** [comment]
this is intentional

**Comment by Fadyio** [comment]
![good](https://github.com/user-attachments/assets/3a07be67-aae7-48ad-bc9d-366da02ee3a3)

as you can see they removed it, shame that they removed opus it was the best model and you can see people crying on the discord server

**Comment by pnd280** [comment]
@michalkkkd perplexity only removed said models from the frontend, with the help of Complexity, we can still use them. Except for Opus where they already locked the usage on the backend

edit: some people are still getting like 1-2 Opus uses over time, so I keep it on the list

**Comment by Fadyio** [comment]
For question, you can not find a single blog about it, I do not know how this company has a value of 9 billion dollars, they add or remove without warning.

**Comment by Fadyio** [comment]
> @michalkkkd perplexity only removed said models from the frontend, with the help of Complexity, we can still use them. Except for Opus where they already locked the usage on the backend

So that means they're going to remove it soon?

**Comment by pnd280** [comment]
@Fadyio perplexity has been known for poorly documenting most of their changes, shipping broken updates from time to time, migrating their frontend architecture and ship numerous breaking bugs without a single announcement. If you're on their discord you'll notice the significant communication gap between the company and its users. Regarding model removals, sometimes they do annouce them sometimes they don't. And yes, they have removed Opus 3, but I strongly believe that it likely serves as placeholder for the upcoming Opus 3.5
