### ISSUE TITLE
[Bug]: An error in the changelog

### ISSUE THREAD

**Issue by SqrtMinusOne** [pnd280/complexity#44]
### Version

0.0.5.11-alpha

### Describe the bug

Hey, not sure where to report it :-)

The changelog says 'Removed Claude 3.5 Opus'; however, this model hasn't been released by Anthropic (and likely won't be).

### Steps to reproduce

1. Open https://github.com/pnd280/complexity/releases/tag/v0.0.5.11-alpha

### Bug confirmation

- [X] I am not able to reproduce the issue with the extension disabled
- [X] I have re-installed the extension and the issue persists

### Expected behavior

The changelog shouldn't include a reference to a non-existent model.

### Browser

Zen Browser 1.0.1a-3

**Comment by pnd280** [comment]
thanks for reporting
