### ISSUE TITLE
[Bug]: When Complexity is enabled the panel for asking follow up is 4 times the size it should hiding half of my screen.

### ISSUE THREAD

**Issue by mikhoul** [pnd280/complexity#46]
### Version

0.0.5.15

### Describe the bug

When Complexity is enabled the panel for asking follow up is 4 times the size it should hiding half of my screen.

As soon I disable Complexity everything is fine, it begun 1-2 days ago.

![image](https://github.com/user-attachments/assets/c6d69533-2966-40a6-9db5-30839220d8f4)

### Steps to reproduce

I just go to Perplexity.ai

### Bug confirmation

- [X] I am not able to reproduce the issue with the extension disabled
- [X] I have re-installed the extension and the issue persists

### Expected behavior

Having the box the original size.

### Screenshots

![image](https://github.com/user-attachments/assets/20092fe3-4794-4e64-a2de-96731c3a75f1)

### Browser

Latest Brave release channel.

**Comment by pnd280** [comment]
this has been fixed in v0.0.5.16 (https://github.com/pnd280/complexity/releases/tag/v0.0.5.16-alpha) and under review by the Chrome web store, you can manually update the extension if you dont want to wait. Follow the instructions here https://github.com/pnd280/complexity/discussions/47
