### ISSUE TITLE
[Bug]: "Edit Query" Text Added to Query Titles

### ISSUE THREAD

**Issue by imadraude** [pnd280/complexity#49]
### Version

0.0.5.17

### Describe the bug

Extension automatically prefixes the text "Edit Query" to query titles. This behavior occurs consistently and is unrelated to user actions.

### Steps to reproduce

1. Start a thread
2. Send more that one query (to invoke query list)

### Bug confirmation

- [x] I am not able to reproduce the issue with the extension disabled
- [X] I have re-installed the extension and the issue persists

### Expected behavior

The query title or related UI elements should display the original query name or content without any additional prefixes.

### Screenshots

![image](https://github.com/user-attachments/assets/ffb75618-12ad-4157-bb29-215b23f04376)

### Browser

Microsoft Edge

**Comment by pnd280** [comment]
fixed https://github.com/pnd280/complexity/releases/tag/v0.0.5.18-alpha
