### ISSUE TITLE
[Feature Request]: Restore Mode Persistence or Add Mode Toggle

### ISSUE THREAD

**Issue by yskmry** [pnd280/complexity#53]
## Issue
After the UI update, the app no longer maintains the previously selected mode (Focus, Writing, etc.) between sessions.

## Request
Either:
1. Restore the previous functionality of remembering the last used mode
2. Add a toggle to lock a preferred mode (especially useful for Writing mode)

Is this Bug or expected behavior by removing feature?
This feature was present in earlier versions and was helpful for maintaining consistent workflow across sessions.

### Use Case

- Improves workflow efficiency
- Reduces repetitive mode selection
- Particularly valuable for users who primarily use one mode (e.g., Writing)

**Comment by hacen-ai** [comment]
+1 verry useful and needed feature

**Comment by pnd280** [comment]
Implemented in v1.1
