### ISSUE TITLE
[Bug]: Thread TOC Not Working 

### ISSUE THREAD

**Issue by thetykuN** [pnd280/complexity#55]
### Version

v1.0.5.0

### Describe the bug

The Thread TOC does not work after the latest upgrade, though it worked in the previous version. I have tried to uninstall and reinstall the extension, and it's still not working. 
![Screenshot 2024-12-18 204126](https://github.com/user-attachments/assets/81c56016-d268-423b-8b91-ca8bf4241a98)

### Steps to reproduce

![image](https://github.com/user-attachments/assets/9fdfcf6b-8370-4d45-a5d4-5cca8fa7b6cc)

### Bug confirmation

- [X] I am not able to reproduce the issue with the extension disabled
- [X] I have re-installed the extension and the issue persists

### Expected behavior

It's supposed to show a Table of Contents (ToCs) for chats with over 2 messages

### Screenshots

![image](https://github.com/user-attachments/assets/15874ac7-dcd4-4483-acf6-e76a7d902df3)

### Browser

Google Chrome latest version

**Comment by pnd280** [comment]
@thetykuN can you confirm whether the ToC shows after refreshing the page or does it not show at all?

**Comment by pnd280** [comment]
c954bfc6bd7270bf95d20140b56caa20d366251b https://github.com/pnd280/complexity/releases/tag/v1.0.6.0

1.0.6 should fix the issue, please reopen if it persists

**Comment by thetykuN** [comment]
Fixed, the TOC is now working, thanks a lot!
