### ISSUE TITLE
[Feature Request]: The option for choosing focus is really hidden

### ISSUE THREAD

**Issue by itsyaasir** [pnd280/complexity#9]
### Feature Description

Hey! Great extension you have, and it has been a lifesaver for me as a Perplexity user.

For the first few days, I had no idea where to select the focus for a certain topic, and whenever I clicked, the internet access didn't provide a hint for selecting the focus. At one point, I had to disable the extension to use the focus.

Today, I discovered that you need to right-click the internet icon to select the focus. Perhaps you could improve the extension by providing a hint or separating the search and focus options.

### Use Case

It will help with user discovering where the option is located

**Comment by pnd280** [comment]
the UI has been redesigned, right click is no longer required
